from otter.test_files import test_case

OK_FORMAT = False

name = "q21"
points = None

@test_case(points=None, hidden=False, 
    success_message="correct!")
def test_random_cmajor_score(env):
  notes = ["C", "D", "E", "F", "G", "A", "B"]
  m21 = env['m21']
  random_cmajor_score = env['random_cmajor_score']
  score = random_cmajor_score(10)

  assert all([isinstance(e, m21.note.Rest) or e.name in notes for e in score.recurse().notesAndRests]), 'Invalid score was generated by random_cmajor_score'
    
